<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Name>Sample</Name>
		<OutputType>Exe</OutputType>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputPath>$(SolutionDir)Build\$(Configuration)\Bin\$(Name)\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ELImGui\ELImGui.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="data.Json.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="data.Text.txt">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
