<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Name>ELImGui</Name>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnforceCodeStyleInBuild>False</EnforceCodeStyleInBuild>
		<Platforms>x64</Platforms>
		<WarningLevel>4</WarningLevel>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputPath>$(SolutionDir)Build\$(Configuration)\Lib\$(Name)\</OutputPath>
		<Configurations>Debug;Release;Debug_Linux;Release_Linux</Configurations>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591;CS1573;CS1712;IDE1006;IDE0044;IDE0072;IDE0010</NoWarn>
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<DebugType>full</DebugType>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<DebugType>full</DebugType>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug_Linux|x64'">
		<DebugType>full</DebugType>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<DefineConstants>$(DefineConstants);LINUX_OS</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release_Linux|x64'">
		<DebugType>full</DebugType>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<DefineConstants>$(DefineConstants);LINUX_OS</DefineConstants>
	</PropertyGroup>

	<ItemGroup>		
		<PackageReference Include="Hexa.NET.GLFW" Version="1.0.4" />
		<PackageReference Include="Hexa.NET.ImGui" Version="2.2.7" />
		<PackageReference Include="Hexa.NET.ImGui.Backends" Version="1.0.15" />
		<PackageReference Include="Hexa.NET.ImGui.Backends.GLFW" Version="1.0.15" />
		<PackageReference Include="Hexa.NET.ImGui.Widgets" Version="1.2.12" />
		<PackageReference Include="Hexa.NET.ImGuizmo" Version="2.2.7" />
		<PackageReference Include="Hexa.NET.ImNodes" Version="2.2.7" />
		<PackageReference Include="Hexa.NET.ImPlot" Version="2.2.7" />
		<PackageReference Include="Hexa.NET.Math" Version="2.0.6" />
		<PackageReference Include="Hexa.NET.Utilities" Version="2.2.2" />
		<PackageReference Include="Hexa.NET.OpenGL3" Version="1.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NLog" Version="6.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Remove="..\..\..\Tools\LServerCodeAnalyzer\Output\LServerCodeAnalyzer.dll" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="font\arialuni.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="font\MaterialSymbolsRounded.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="font\NanumGothicCoding.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	  <None Update="font\seguiemj.ttf">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
